const $=(s,e=document)=>e.querySelector(s);const app=$("#app");
const THEME_KEY="iphone18proTheme.v4",FAV_KEY="iphone18proFavorites.v4",RECIPE_KEY="iphone18proRecipeFavorites.v2";
const state={db:null,q:"",filter:"all",mode:localStorage.getItem('iphone18proMode.v2')||"photo",fav:new Set(JSON.parse(localStorage.getItem(FAV_KEY)||"[]")),recipeFav:new Set(JSON.parse(localStorage.getItem(RECIPE_KEY)||"[]"))};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const route=()=>{const p=(location.hash.replace(/^#/,'')||'/').split('/').filter(Boolean);if(p[0]==='scene'&&p[1])return{name:'scene',id:p[1]};if(p[0]==='recipe'&&p[1])return{name:'recipe',id:p[1]};if(p[0]==='guide')return{name:'guide'};if(p[0]==='capture')return{name:'capture'};if(p[0]==='edit')return{name:'edit'};return{name:'all'}};
function save(){localStorage.setItem(FAV_KEY,JSON.stringify([...state.fav]));localStorage.setItem(RECIPE_KEY,JSON.stringify([...state.recipeFav]));}
function toggle(set,id){set.has(id)?set.delete(id):set.add(id);save();render()}
function setMode(id){state.mode=id;localStorage.setItem('iphone18proMode.v2',id);render()}
function setTheme(name){document.documentElement.dataset.theme=name;localStorage.setItem(THEME_KEY,name);document.querySelectorAll('[data-theme]').forEach(b=>b.classList.toggle('active',b.dataset.theme===name));document.querySelector('meta[name=theme-color]')?.setAttribute('content',{light:'#f3f1ec',dark:'#121110',outdoor:'#fff'}[name])}
const badge=(s,tag)=>`<span class="badge ${tag?'badge-link':''}" ${tag?`data-tag-filter="${esc(tag)}"`:''}>${esc(s)}</span>`;
const CAPTURE_LABELS={
 aperture:['🔘','光圈','Aperture'],depth:['👤','景深','Depth'],shutter:['⏱️','快門速度','Shutter Speed'],night:['🌙','夜間模式','Night Mode'],ev:['☀️','曝光','Exposure'],focus:['🎯','對焦','Focus'],wb:['🌡️','白平衡','White Balance'],zoom:['🔭','鏡頭／變焦','Lens / Zoom'],mp:['🖼️','解析度','Resolution'],format:['💾','格式','Format'],style:['🎨','攝影風格','Photographic Style'],texture:['🧵','質感','Texture'],grain:['🎞️','顆粒','Grain'],tone:['🎚️','色調','Tone'],histogram:['📊','長條圖','Histogram'],live:['🔴','原況照片','Live Photo'],burst:['📸','連拍','Burst'],timer:['⏲️','計時器','Timer'],grid:['▦','格線／水平儀','Grid / Level'],['portrait-mode']:['👤','人像模式','Portrait Mode'],macro:['🔬','微距','Macro'],tripod:['🦿','腳架','Tripod'],flash:['⚡','閃光燈','Flash'],aspect:['▣','畫面比例','Aspect Ratio']};
const EDIT_LABELS={exposure:['☀️','曝光','Exposure'],brilliance:['✨','鮮明度','Brilliance'],highlights:['🔆','亮部','Highlights'],shadows:['🌘','陰影','Shadows'],contrast:['◐','對比度','Contrast'],brightness:['💡','亮度','Brightness'],'black-point':['⚫','黑點','Black Point'],saturation:['🎨','飽和度','Saturation'],vibrance:['🌈','自然飽和度','Vibrance'],warmth:['🌡️','色溫','Warmth'],tint:['🟣','色調','Tint'],sharpness:['🔪','銳度','Sharpness'],definition:['🔎','清晰度','Definition'],'noise-reduction':['🧹','雜訊消除','Noise Reduction'],vignette:['◉','暈影','Vignette']};
const CAPTURE_GROUPS={optical:'鏡頭',computational:'人像',exposure:'曝光',focus:'對焦',color:'色彩',lens:'鏡頭',format:'格式',style:'風格',monitoring:'曝光監察','capture-mode':'拍攝功能',composition:'構圖',accessory:'器材',lighting:'光線'};
const EFFECT_TAGS={natural:'自然',bright:'明亮',cool:'冷色',warm:'暖色',drama:'戲劇',japanese:'日系'};
const SCENE_TAGS={'sunrise':['光線','暖色'],'blue-sky':['風景','明亮'],overcast:['風景','冷色'],sunset:['光線','暖色'],'milky-way':['夜景','冷色'],moon:['夜景'],'city-night':['夜景','暖色'],'car-trails':['夜景','動態'],'silky-water':['風景','水'],'water-splash':['風景','動態'],'starburst':['夜景'],'backlight':['光線'],portrait:['人物'],'env-portrait':['人物'],'tilt-shift':['風景'],'japanese-fresh':['日系','明亮'],mountain:['風景'],seascape:['風景','暖色'],fog:['風景','冷色'],architecture:['風景'],street:['風景'],sports:['動態'],food:['食物','暖色'],macro:['微距','自然'],'video-24p':['影片']};
function dataMaps(){const d=state.db;return{scenes:new Map(d.scenes.scenes.map(x=>[x.id,x])),styles:new Map(d.styles.styles.map(x=>[x.id,x])),recipes:new Map(d.recipes.recipes.map(x=>[x.id,x])),workflows:new Map(d.workflows.workflows.map(x=>[x.id,x]))}}
function sceneTitle(s){return s.title||s.name}
function stageTag(stage){return stage==='capture'?badge('📷 拍攝','拍攝'):badge('✏️ 後製','後製')}
function captureName(id){const x=CAPTURE_LABELS[id];return x?`${x[0]} ${x[1]} (${x[2]})`:id}
function editName(id){const x=EDIT_LABELS[id];return x?`${x[0]} ${x[1]} (${x[2]})`:id}
function cleanValue(id,value){if(id==='histogram')return '';if(id==='format')return String(value).replace(/HEIF Max 或 /g,'');if(id==='aspect')return String(value);return value}
function oneGlanceCapture(s){const rows=[...(s.must||[]),...(s.options||[])].filter(r=>!['style','histogram','format','aspect'].includes(r.id));const seen=new Set();return rows.map(r=>{if(seen.has(r.id))return null;seen.add(r.id);const v=cleanValue(r.id,r.value);return v?`${captureName(r.id).split(' (')[0]} ${v}`:null}).filter(Boolean).slice(0,5).join(' · ')}
function sceneTags(s){return ['📷 拍攝',...(SCENE_TAGS[s.id]||s.categories?.map(c=>c.name)||[])].map(x=>badge(x,x==='📷 拍攝'?'拍攝':x)).join('')}
function recipeTags(r){const extra=r.id.startsWith('japanese-')?['日系']:[];return ['✏️ 後製',...(r.familyTags||[]).map(x=>EFFECT_TAGS[x]||x),...extra].filter((x,i,a)=>a.indexOf(x)===i).map(x=>badge(x,x==='✏️ 後製'?'後製':x)).join('')}
function searchable(blob){const q=state.q.trim().toLowerCase();return !q||JSON.stringify(blob).toLowerCase().includes(q)}
function tagFilterOk(tags){if(state.filter==='all')return true;if(state.filter==='favorites')return true;return tags.map(String).some(x=>x.toLowerCase()===state.filter.toLowerCase())}
function sceneCard(s){const on=state.fav.has(s.id);return `<article class="item-card card" data-open="scene/${s.id}"><button class="fav ${on?'on':''}" data-fav="${s.id}" aria-label="收藏">${on?'★':'☆'}</button><a href="#/scene/${s.id}"><img class="shot" src="examples/${s.id}.jpg" alt=""><div class="pad"><div class="badges">${sceneTags(s)}</div><h2>${esc(sceneTitle(s))}</h2><p class="item-description">${esc(s.description||`針對「${sceneTitle(s)}」的實用拍攝設定。`)}</p><p class="one-glance"><b>一眼睇晒</b><br>${esc(oneGlanceCapture(s)||'按入查看拍攝設定')}</p></div></a></article>`}
function recipeCard(r){const on=state.recipeFav.has(r.id);return `<article class="item-card card" data-open="recipe/${r.id}"><button class="fav ${on?'on':''}" data-recipe-fav="${r.id}" aria-label="收藏">${on?'★':'☆'}</button>${r.image?`<img class="shot" src="${esc(r.image)}" alt="">`:''}<div class="pad"><div class="badges">${recipeTags(r)}</div><h2>${esc(r.name)}</h2><p class="item-description">${esc(r.fit||r.want||'後製調色方案，可按原片及個人喜好套用。')}</p><p class="one-glance"><b>一眼睇晒</b><br>${esc(r.line||'查看完整後製調校')}</p><a class="btn" href="#/recipe/${r.id}">查看調校</a></div></article>`}
function modes(){return [['timelapse','⏱️','縮時','Time-lapse'],['slomo','🐢','慢動作','Slo-mo'],['cinematic','🎬','電影','Cinematic'],['video','🎥','影片','Video'],['photo','📷','照片','Photo'],['portrait','👤','人像','Portrait'],['spatial','🕶️','空間','Spatial'],['pano','🌐','全景','Pano']]}
function modeSelector(){return `<section class="mode-panel card"><div class="section-head"><div><div class="eyebrow">拍攝模式</div><h2>選擇目前使用的模式</h2></div><span class="mode-current">${esc((modes().find(x=>x[0]===state.mode)||modes()[4])[2])}</span></div><div class="mode-grid">${modes().map(([id,icon,zh,en])=>`<button class="mode-btn ${state.mode===id?'active':''}" data-mode="${id}"><span class="mode-icon">${icon}</span><span><b>${zh}</b><small>${en}</small></span></button>`).join('')}</div>${state.mode==='portrait'?`<div class="portrait-lights"><strong>👤 人像光效 (Portrait Lighting)</strong><div class="light-grid">${['自然光 Natural','攝影室光 Studio','輪廓光 Contour','舞台光 Stage','舞台單色 Stage Mono','高調單色 High-Key Mono'].map((x,i)=>`<span>${i+1} · ${x}</span>`).join('')}</div></div>`:''}</section>`}
function filters(){const row1=[['all','▦ 全部'],['favorites','☆ 收藏'],['capture','📷 拍攝'],['edit','✏️ 後製']];const row2=[['自然','🌿 自然'],['明亮','☀️ 明亮'],['冷色','❄️ 冷色'],['暖色','🔥 暖色'],['戲劇','🎭 戲劇'],['日系','🌸 日系'],['風景','🏞️ 風景'],['夜景','🌙 夜景'],['人物','👤 人物'],['動態','🏃 動態'],['水','💧 水'],['光線','💡 光線']];const row=(items,cls)=>`<div class="filter-row ${cls}">${items.map(([id,label])=>`<button class="chip ${state.filter===id?'active':''}" data-filter="${id}">${esc(label)}${id==='favorites'?' '+(state.fav.size+state.recipeFav.size):''}</button>`).join('')}</div>`;return `<div class="filters">${row(row1,'filter-primary')}${row(row2,'filter-secondary')}</div>`}
function allPage(active='all'){
 const d=state.db;
 const scenes=d.scenes.scenes.filter(s=>searchable(s)&&(!['favorites'].includes(state.filter)||state.fav.has(s.id))&&state.filter!=='edit'&&tagFilterOk(['拍攝',...(SCENE_TAGS[s.id]||[])]));
 const recipes=d.recipes.recipes.filter(r=>searchable(r)&&(!['favorites'].includes(state.filter)||state.recipeFav.has(r.id))&&state.filter!=='capture'&&tagFilterOk(['後製',...(r.familyTags||[]).map(x=>EFFECT_TAGS[x]||x)]));
 const isCapture=active==='capture'||state.filter==='capture',isEdit=active==='edit'||state.filter==='edit';
 const sceneList=isEdit?[]:scenes,recipeList=isCapture?[]:recipes;
 let body='';if(!isEdit)body+=`<section class="item-section"><div class="section-head"><div><h2>📷 拍攝項目</h2></div><span class="count">${sceneList.length}</span></div><div class="item-grid">${sceneList.map(sceneCard).join('')||'<div class="empty">沒有符合的拍攝項目。</div>'}</div></section>`;if(!isCapture)body+=`<section class="item-section"><div class="section-head"><div><h2>✏️ 後製項目</h2></div><span class="count">${recipeList.length}</span></div><div class="item-grid">${recipeList.map(recipeCard).join('')||'<div class="empty">沒有符合的後製項目。</div>'}</div></section>`;
 return `<div class="search"><input id="q" type="search" placeholder="搜尋名稱、參數、設定……" value="${esc(state.q)}"></div>${filters()}${body}<p class="guide-link"><a class="btn" href="#/guide">📖 通用功能調校方式／定義</a></p>`}
function dataMaps(){const d=state.db;return{scenes:new Map(d.scenes.scenes.map(x=>[x.id,x])),styles:new Map(d.styles.styles.map(x=>[x.id,x])),recipes:new Map(d.recipes.recipes.map(x=>[x.id,x])),workflows:new Map(d.workflows.workflows.map(x=>[x.id,x]))}}
function sceneTitle(s){return s.title||s.name}
function stageTag(stage){return stage==='capture'?badge('📷 拍攝'):badge('✏️ 後製')}
function captureName(id){const x=CAPTURE_LABELS[id];return x?`${x[0]} ${x[1]} (${x[2]})`:id}
function editName(id){const x=EDIT_LABELS[id];return x?`${x[0]} ${x[1]} (${x[2]})`:id}
function cleanValue(id,value){if(id==='histogram')return '';if(id==='format')return String(value).replace(/HEIF Max 或 /g,'');if(id==='aspect')return String(value);return value}
function oneGlanceCapture(s){const rows=[...(s.must||[]),...(s.options||[])].filter(r=>!['style','histogram','format','aspect'].includes(r.id));const seen=new Set();return rows.map(r=>{if(seen.has(r.id))return null;seen.add(r.id);const v=cleanValue(r.id,r.value);return v?`${captureName(r.id).split(' (')[0]} ${v}`:null}).filter(Boolean).slice(0,5).join(' · ')}
function sceneTags(s){return ['📷 拍攝',...(SCENE_TAGS[s.id]||s.categories?.map(c=>c.name)||[])].map(x=>badge(x,x==='📷 拍攝'?'拍攝':x)).join('')}
function recipeTags(r){const extra=r.id.startsWith('japanese-')?['日系']:[];return ['✏️ 後製',...(r.familyTags||[]).map(x=>EFFECT_TAGS[x]||x),...extra].filter((x,i,a)=>a.indexOf(x)===i).map(x=>badge(x,x==='✏️ 後製'?'後製':x)).join('')}
function searchable(blob){const q=state.q.trim().toLowerCase();return !q||JSON.stringify(blob).toLowerCase().includes(q)}
function tagFilterOk(tags){if(state.filter==='all')return true;if(state.filter==='favorites')return true;return tags.map(String).some(x=>x.toLowerCase()===state.filter.toLowerCase())}
function sceneCard(s){const on=state.fav.has(s.id);return `<article class="item-card card" data-open="scene/${s.id}"><button class="fav ${on?'on':''}" data-fav="${s.id}" aria-label="收藏">${on?'★':'☆'}</button><a href="#/scene/${s.id}"><img class="shot" src="examples/${s.id}.jpg" alt=""><div class="pad"><div class="badges">${sceneTags(s)}</div><h2>${esc(sceneTitle(s))}</h2><p class="item-description">${esc(s.description||`針對「${sceneTitle(s)}」的實用拍攝設定。`)}</p><p class="one-glance"><b>一眼睇晒</b><br>${esc(oneGlanceCapture(s)||'按入查看拍攝設定')}</p></div></a></article>`}
function recipeCard(r){const on=state.recipeFav.has(r.id);return `<article class="item-card card" data-open="recipe/${r.id}"><button class="fav ${on?'on':''}" data-recipe-fav="${r.id}" aria-label="收藏">${on?'★':'☆'}</button>${r.image?`<img class="shot" src="${esc(r.image)}" alt="">`:''}<div class="pad"><div class="badges">${recipeTags(r)}</div><h2>${esc(r.name)}</h2><p class="item-description">${esc(r.fit||r.want||'後製調色方案，可按原片及個人喜好套用。')}</p><p class="one-glance"><b>一眼睇晒</b><br>${esc(r.line||'查看完整後製調校')}</p><a class="btn" href="#/recipe/${r.id}">查看調校</a></div></article>`}
function modes(){return [['timelapse','⏱️','縮時','Time-lapse'],['slomo','🐢','慢動作','Slo-mo'],['cinematic','🎬','電影','Cinematic'],['video','🎥','影片','Video'],['photo','📷','照片','Photo'],['portrait','👤','人像','Portrait'],['spatial','🕶️','空間','Spatial'],['pano','🌐','全景','Pano']]}
function modeSelector(){return `<section class="mode-panel card"><div class="section-head"><div><div class="eyebrow">拍攝模式</div><h2>選擇目前使用的模式</h2></div><span class="mode-current">${esc((modes().find(x=>x[0]===state.mode)||modes()[4])[2])}</span></div><div class="mode-grid">${modes().map(([id,icon,zh,en])=>`<button class="mode-btn ${state.mode===id?'active':''}" data-mode="${id}"><span class="mode-icon">${icon}</span><span><b>${zh}</b><small>${en}</small></span></button>`).join('')}</div>${state.mode==='portrait'?`<div class="portrait-lights"><strong>👤 人像光效 (Portrait Lighting)</strong><div class="light-grid">${['自然光 Natural','攝影室光 Studio','輪廓光 Contour','舞台光 Stage','舞台單色 Stage Mono','高調單色 High-Key Mono'].map((x,i)=>`<span>${i+1} · ${x}</span>`).join('')}</div></div>`:''}</section>`}
function filters(tags){const primary=[['all','▦ 全部'],['favorites','☆ 收藏'],['capture','📷 拍攝'],['edit','✏️ 後製']];const secondary=tags.filter(([id])=>!['all','favorites','capture','edit'].includes(id));const row=(items,cls)=>`<div class="filter-row ${cls}">${items.map(([id,label])=>`<button class="chip ${state.filter===id?'active':''}" data-filter="${id}">${esc(label)}${id==='favorites'?' '+(state.fav.size+state.recipeFav.size):''}</button>`).join('')}</div>`;return `<div class="filters">${row(primary,'filter-primary')}${row(secondary,'filter-secondary')}</div>`}
function topTabs(active){return ``}
function allPage(active='all'){
 const d=state.db, scenes=d.scenes.scenes.filter(s=>searchable(s)&&(!['favorites'].includes(state.filter)||state.fav.has(s.id))&&tagFilterOk(['拍攝',...(SCENE_TAGS[s.id]||[])])), recipes=d.recipes.recipes.filter(r=>searchable(r)&&(!['favorites'].includes(state.filter)||state.recipeFav.has(r.id))&&tagFilterOk(['後製',...(r.familyTags||[]).map(x=>EFFECT_TAGS[x]||x)]));
 const tags=[['拍攝','拍攝'],['後製','後製'],['自然','自然'],['明亮','明亮'],['冷色','冷色'],['暖色','暖色'],['戲劇','戲劇'],['日系','日系'],['風景','風景'],['夜景','夜景'],['人物','人物'],['動態','動態']];
 let body='';if(active!=='edit')body+=`<section class="item-section"><div class="section-head"><div><div class="eyebrow">${active==='capture'?'Camera':'全部'}</div><h2>📷 拍攝項目</h2><p class="muted">場景是獨立項目；不再於場景內指定風格或後製。</p></div><span class="count">${scenes.length}</span></div><div class="item-grid">${scenes.map(sceneCard).join('')||'<div class="empty">沒有符合的拍攝項目。</div>'}</div></section>`;if(active!=='capture')body+=`<section class="item-section"><div class="section-head"><div><div class="eyebrow">${active==='edit'?'Photos':'全部'}</div><h2>✏️ 後製項目</h2><p class="muted">每個方案只列 Photos 的後製調校，不再拆成另一套 Style → Tone / Color / Palette / Texture。</p></div><span class="count">${recipes.length}</span></div><div class="item-grid">${recipes.map(recipeCard).join('')||'<div class="empty">沒有符合的後製項目。</div>'}</div></section>`;
 return `<div class="search"><input id="q" type="search" placeholder="搜尋名稱、參數、設定……" value="${esc(state.q)}"></div>${filters(tags)}${body}<p class="guide-link"><a class="btn" href="#/guide">📖 通用功能調校方式／定義</a></p>`}
function relevantCaptureRows(rows){return (rows||[]).filter(r=>!['style','histogram','format','aspect'].includes(r.id))}
function captureRows(rows,params){const clean=relevantCaptureRows(rows);if(!clean.length)return '<p class="muted">沒有需要額外設定的項目。</p>';return `<div class="table-scroll"><table class="settings-table"><thead><tr><th>參數</th><th>設定</th><th>原因</th></tr></thead><tbody>${clean.map(r=>{const p=params.get(r.id);return `<tr><td>${captureName(r.id)}</td><td><strong>${esc(r.value)}</strong></td><td>${esc(r.why||'')}</td></tr>`}).join('')}</tbody></table></div>`}
function editRows(adj){return `<div class="table-scroll"><table class="settings-table"><thead><tr><th>參數</th><th>調校</th></tr></thead><tbody>${Object.entries(adj).map(([k,v])=>`<tr><td>${editName(k)}</td><td><strong>${esc(v)}</strong></td></tr>`).join('')}</tbody></table></div>`}
function scenePage(id){const d=state.db,m=dataMaps(),s=m.scenes.get(id);if(!s)return `<div class="empty">找不到場景。</div>`;const params=new Map(d.parameters.parameters.map(x=>[x.id,x]));const on=state.fav.has(id);return `<a class="back" href="#/capture">← 拍攝</a><header class="detail-head"><div><div class="badges">${sceneTags(s)}</div><h1>${esc(sceneTitle(s))}</h1><p class="lead">${esc(s.description||`適用於${sceneTitle(s)}的現場拍攝。`)}</p></div><div class="actions"><button class="btn" data-fav="${id}">${on?'★ 已收藏':'☆ 收藏'}</button></div></header>${modeSelector()}<img class="shot hero-shot" src="examples/${id}.jpg" alt="${esc(sceneTitle(s))}"><section class="info-strip"><div><b>簡單說明</b><span>${esc(s.description||'針對此場景的實用拍攝設定。')}</span></div><div><b>適合場景</b><span>${esc(s.fit||'按主體、光線及構圖需要選擇。')}</span></div><div><b>避免事項</b><span>${esc(s.avoid||'避免過度調校及不必要的後期補救。')}</span></div></section><section class="detail-section"><div class="section-head"><div><h2>📷 必須</h2><p class="muted">先完成以下 ${relevantCaptureRows(s.must).length} 項</p></div></div>${captureRows(s.must||[],params)}</section><section class="detail-section"><div class="section-head"><div><h2>⚙️ 選項</h2><p class="muted">有需要時再加入以下設定</p></div></div>${captureRows(s.options||[],params)}</section><section class="detail-section"><h2>操作次序</h2><ol class="flow-list">${(s.flow||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section><section class="detail-section"><h2>注意事項</h2><ul class="notes">${(s.notes||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`}
function recipePage(id){const r=dataMaps().recipes.get(id);if(!r)return `<div class="empty">找不到後製項目。</div>`;const style='Photos Style';return `<a class="back" href="#/edit">← 後製</a><header class="detail-head"><div><div class="badges">${recipeTags(r)}</div><h1>${esc(r.name)}</h1><p class="lead">${esc(r.line||r.want||'後製調校方案')}</p></div><div class="actions"><button class="btn" data-recipe-fav="${id}">${state.recipeFav.has(id)?'★ 已收藏':'☆ 收藏'}</button></div></header>${r.image?`<img class="shot hero-shot" src="${esc(r.image)}" alt="">`:''}<section class="info-strip"><div><b>簡介</b><span>${esc(r.want||r.line||'')}</span></div><div><b>適合場景</b><span>${esc(r.fit||'按原片光線及主體選擇。')}</span></div><div><b>避免事項</b><span>${esc(r.avoid||'避免過度調校。')}</span></div></section><section class="detail-section"><h2>🎨 Style（Photos）</h2><p class="muted">Photos 後製的 Style 與相機的 Photographic Style 是兩套不同控制；後製只保留 <b>0–100</b> 的風格強度，不再調校 Tone、Color、Palette、Texture。</p><div class="style-intensity"><span>🎨 風格強度（Style）</span><strong>0–100</strong></div><input class="style-range" type="range" min="0" max="100" value="50" aria-label="Photos Style 風格強度"><div class="range-labels"><span>0</span><span>50</span><span>100</span></div></section><section class="detail-section"><h2>✏️ Edit 調校</h2>${editRows(r.adjustments||{})}</section><section class="detail-section"><h2>其他</h2>${r.extras?`<div class="control-list">${Object.entries(r.extras).map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>`:'<p class="muted">沒有額外設定。</p>'}</section>`}
function guidePage(){const d=state.db;const params=d.parameters.parameters;const hist=`<section class="guide-card card pad"><h2>📊 長條圖 (Histogram)</h2><p>用於判斷曝光分布，不是「長開＝設定開」的場景參數。</p><div class="hist-guide"><div><b>貼近左邊</b><span>暗部較多；留意陰影死黑。</span></div><div><b>集中中間</b><span>整體曝光較均衡。</span></div><div><b>貼近右邊</b><span>亮部較多；留意高光爆光。</span></div></div></section>`;const format=`<section class="guide-card card pad"><h2>💾 格式 (Format) ＋ ▣ 畫面比例 (Aspect Ratio)</h2><p><b>4:3</b>：一般拍攝建議，保留較完整原生畫面。<b>48MP</b>：光線充足及需要裁切時使用。<b>ProRAW</b>：需要較大幅後期時使用。</p></section>`;return `<section class="hero compact-hero"><div class="eyebrow">General Guide</div><h1>通用功能調校方式／定義</h1><p>不屬於任何單一場景的設定集中於此。場景頁只顯示該場景真正有分別的必須及選項。</p></section>${hist}${format}<section class="guide-card card pad"><h2>📷 Camera 調校參數</h2><div class="guide-grid">${params.map(p=>`<article><h3>${captureName(p.id)}</h3><p>${esc(p.note||'拍攝時的相應控制。')}</p></article>`).join('')}</div></section><section class="guide-card card pad"><h2>✏️ Photos Edit 調校</h2><div class="guide-grid">${Object.entries(EDIT_LABELS).map(([id,x])=>`<article><h3>${x[0]} ${x[1]} (${x[2]})</h3><p>Photos 後製滑桿，數值按需要微調；與 Camera 拍攝時的同名控制分開。</p></article>`).join('')}</div></section>`}
function render(){if(!state.db)return;const r=route();document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===r.name));if(r.name==='scene')app.innerHTML=scenePage(r.id);else if(r.name==='recipe')app.innerHTML=recipePage(r.id);else if(r.name==='guide')app.innerHTML=guidePage();else app.innerHTML=allPage(r.name);$('#q')?.addEventListener('input',e=>{state.q=e.target.value;render()});}
window.addEventListener('hashchange',render);document.addEventListener('click',e=>{const tag=e.target.closest('[data-tag-filter]');if(tag){e.preventDefault();e.stopPropagation();state.filter=tag.dataset.tagFilter;render();return}const open=e.target.closest('[data-open]');if(open&&!e.target.closest('button,a,[data-tag-filter]')){location.hash='#/'+open.dataset.open;return}const f=e.target.closest('[data-fav]');if(f){e.preventDefault();toggle(state.fav,f.dataset.fav);return}const rf=e.target.closest('[data-recipe-fav]');if(rf){e.preventDefault();toggle(state.recipeFav,rf.dataset.recipeFav);return}const mode=e.target.closest('[data-mode]');if(mode){e.preventDefault();setMode(mode.dataset.mode);return}const fl=e.target.closest('[data-filter]');if(fl){e.preventDefault();state.filter=fl.dataset.filter;render();return}const th=e.target.closest('[data-theme]');if(th){e.preventDefault();setTheme(th.dataset.theme);return}});
async function boot(){try{const files=['categories','hardware','parameters','scenes','styles','recipes','adjustments','japanese-adjustment-presets','workflows','recipe-migration-map'];const entries=await Promise.all(files.map(async n=>[n,await fetch(`data/${n}.json`).then(r=>r.json())]));state.db=Object.fromEntries(entries);setTheme(localStorage.getItem(THEME_KEY)||'light');render()}catch(err){app.innerHTML=`<div class="error"><h1>資料載入失敗</h1><p>${esc(err.message)}</p></div>`}}
boot();
